symbols:
  - CBA.AX
  - BHP.AX
  - CSL.AX
  - NAB.AX
  - WBC.AX
  - ANZ.AX
  - MQG.AX
  - WES.AX
  - WOW.AX
  - TCL.AX
  - RMD.AX
  - TLS.AX
  - COL.AX
  - STO.AX
  - FMG.AX
  - GMG.AX
  - ALL.AX
  - COH.AX
  - CPU.AX
  - ASX.AX
  - WDS.AX
  - RIO.AX
  - SUN.AX
  - QBE.AX
  - IAG.AX
  - REA.AX
  - WTC.AX
  - XRO.AX
  - BXB.AX
  - ORG.AX
  - S32.AX
  - AMC.AX
  - ALD.AX
  - MIN.AX
  - CAR.AX
  - SOL.AX
  - AKE.AX
  - EDV.AX
  - GPT.AX
  - CHC.AX
  - MFG.AX
  - JBH.AX
  - SGP.AX
  - SCG.AX
  - SEK.AX
  - SHL.AX
  - MP1.AX
  - APA.AX
  - NST.AX
  - NXT.AX
  - LLC.AX
  - TWE.AX
  - MPL.AX
  - BSL.AX
  - TPG.AX
  - AIA.AX
  - EVN.AX
  - ORI.AX
  - HVN.AX
  - CCL.AX
  - MTS.AX
  - WOR.AX
  - BEN.AX
  - DMP.AX
  - JHX.AX
  - ILU.AX
  - SFR.AX
  - PMV.AX
  - AZJ.AX
  - GQG.AX
