symbols:
  - SAP.DE
  - SIE.DE
  - ALV.DE
  - IFX.DE
  - MUV2.DE
  - RWE.DE
  - BMW.DE
  - DB1.DE
  - ADS.DE
  - BAS.DE
  - DHL.DE
  - DTE.DE
  - HEN3.DE
  - EOAN.DE
  - VOW3.DE
  - MBG.DE
  - SHL.DE
  - MTX.DE
  - BEI.DE
  - FRE.DE
  - QIA.DE
  - ENR.DE
  - HEI.DE
  - PUM.DE
  - CON.DE
  - PAH3.DE
  - 1COV.DE
  - ZAL.DE
  - HNR1.DE
  - MRK.DE
  - SY1.DE
  - AIR.DE
  - MTU.DE
  - VNA.DE
  - LEG.DE
  - TKA.DE
  - BNR.DE
  - CBK.DE
  - DBK.DE
  - SRT3.DE
  - GXI.DE
  - FME.DE
