symbols:
  - SAP.DE
  - SIE.DE
  - ALV.DE
  - MUV2.DE
  - DTE.DE
  - DB1.DE
  - IFX.DE
  - BAS.DE
  - ADS.DE
  - MRK.DE
  - BMW.DE
  - RWE.DE
  - AIR.DE
  - SHL.DE
  - HEN3.DE
  - BEI.DE
  - CON.DE
  - DTG.DE
  - VOW3.DE
  - ENR.DE
